name: 'Generate Contracts'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      - src/**

jobs:
  generate_posting:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout contracts
        uses: actions/checkout@v3
        with:
          path: contracts
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      
      - name: Checkout python version
        run: python -V

      - name: Checkout python version
        run: pip install -r ${GITHUB_WORKSPACE}/contracts/requirements.txt


      - name: Update the privilege 
        run: chmod +x ${GITHUB_WORKSPACE}/contracts/deploy.sh
        
      - name: Execute deploy scripts
        run: ${GITHUB_WORKSPACE}/contracts/deploy.sh
        shell: bash

      - name: Generating file
        run: |
          printf "Hello\nWorld\n`date`\n" > ${GITHUB_WORKSPACE}/contracts/hello.txt

      - name: Commit files
        run: |
          cd ${GITHUB_WORKSPACE}/contracts
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${GITHUB_WORKSPACE}/contracts/hello.txt
          git commit -a -m "[github action generating posting lib]"
          git checkout -b dev-posting-lib
          git push -f origin dev-posting-lib
      
      - name: Create Python Posting lib Pull Request
        uses: peter-evans/create-pull-request@v4


