name: 'Generate Contracts'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      - src/**
permissions: write-all

jobs:
  generate_posting:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout contracts
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          path: contracts
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      
      - name: Checkout python version
        run: python -V

      - name: Checkout python version
        run: pip install -r ${GITHUB_WORKSPACE}/contracts/requirements.txt


      - name: Update the privilege 
        run: chmod +x ${GITHUB_WORKSPACE}/contracts/deploy.sh
        
      - name: Execute deploy scripts
        run: ${GITHUB_WORKSPACE}/contracts/deploy.sh
        shell: bash

      - name: Generating file
        run: |
          python -c "import uuid; print(uuid.uuid4())" > ${GITHUB_WORKSPACE}/contracts/random.txt

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY }} 
      #     known_hosts: 'github.com'

      # - name: Commit files
      #   run: |
      #     cd ${GITHUB_WORKSPACE}/contracts
      #     git config --global user.email "qinjet@gmail.com"
      #     git config --global user.name "JetQin"
      #     git add ${GITHUB_WORKSPACE}/contracts/random.txt
      #     git commit -a -m "[github action generating posting lib]"
      #     git checkout -b dev-posting-lib
      #     git push origin dev-posting-lib

      - name: print log
        run: |
          echo hello v3     

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          directory: contracts
          branch: dev-posting-lib
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: devops-cloud-connect/github-action-demo

      # - name: Create Python Posting lib Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     commit-message: Creating posting lib
      #     title: Generating posting lib
      #     base: main
      #     labels: postings
      #     branch: dev-posting-lib

      - name: Create Python Posting lib Pull Request
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev-posting-lib
          target_branch: main
          title: Generating posting lib
     