name: 'Deploy Contracts'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

jobs:
  setup:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout contracts
        uses: actions/checkout@v3
        with:
          path: contracts
     
      - name: Print ssh key
        run: echo ${{ secrets.SSH-KEY }} \
             echo ${{ github.token }}
        
      - name: Check out sdk repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: sdk
          repository: JetQin/contract-sdk
          token: ${{ secrets.DEPLOY_KEY }}
          #token: ${{ github.token }}
          #ssh-key: ${{ secrets.SSH_KEY }}
          #persist-credentials: true

          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # cache pip dependencies
      
      - name: Install python dependencies
        run: pip install -r ${GITHUB_WORKSPACE}/sdk/requirements.txt
     
      - name: Update the privilege 
        run: chmod +x ${GITHUB_WORKSPACE}/contracts/deploy.sh
        
      - name: Execute deploy scripts
        run: ${GITHUB_WORKSPACE}/contracts/deploy.sh
        shell: bash

     
