name: 'Generate Contracts'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      - src/**

jobs:
  generate_posting:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout contracts
        uses: actions/checkout@v3
        with:
          path: contracts
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      
      - name: Checkout python version
        run: python -V

      - name: Update the privilege 
        run: chmod +x ${GITHUB_WORKSPACE}/contracts/deploy.sh
        
      - name: Execute deploy scripts
        run: ${GITHUB_WORKSPACE}/contracts/deploy.sh
        shell: bash

      - name: Generating file
        run: echo "Hello" > ${GITHUB_WORKSPACE}/contracts/hello.txt
        shell: bash

      - name: Commit files # transfer the postings.py to repo
        run: |
          cd ${GITHUB_WORKSPACE}/source/contracts/
          git add ${GITHUB_WORKSPACE}/source/contracts/hello.txt
          git commit -m "add postings file"

      - name: Push changes # push the postings to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true




