name: 'Deploy Contracts'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      - .github/workflows/github-deploy-demo.yaml

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

jobs:
  prepare_env:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout contracts
        uses: actions/checkout@v3
        with:
          path: contracts

      - name: Decrypt keys
        run: ${GITHUB_WORKSPACE}/contracts/decrypt_secret.sh
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        
      - name: Test printing your secret (Remove this step in production)
        run: cat ${GITHUB_WORKSPACE}/contracts/my_secret.json

      - name: Check out sdk repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: sdk
          repository: JetQin/contract-sdk
          token: ${{ secrets.SDK_READ_KEY }}
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # cache pip dependencies
      
      - name: Install python dependencies
        run: pip install -r ${GITHUB_WORKSPACE}/sdk/requirements.txt
     
      - name: Update the privilege 
        run: chmod +x ${GITHUB_WORKSPACE}/contracts/deploy.sh
        
      - name: Execute deploy scripts
        run: ${GITHUB_WORKSPACE}/contracts/deploy.sh
        shell: bash

     
